# -*- coding: utf-8 -*-
"""python currency_converter.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Va8uf7X8HZmrxBWsAr4D4LQM8Ri0AJvk
"""

import requests  # For fetching live exchange rates from the web
import matplotlib.pyplot as plt  # For drawing a cool trend chart
from datetime import datetime  # To add timestamps if we expand

# Step 1: Fetch latest rates (free API, no signup needed)
def fetch_latest_rates(base_currency):
    """Grabs exchange rates for 170+ currencies from a reliable free API."""
    url = f"https://api.exchangerate-api.com/v4/latest/{base_currency}"
    try:
        response = requests.get(url)
        response.raise_for_status()  # Checks for network errors
        data = response.json()
        return data['rates']
    except Exception as e:
        print(f"Oops! Couldn't fetch rates: {e}")
        return None

# Step 2: Do the math for conversion
def convert_money(base, target, amount):
    """Converts your amount using live rates. Returns None if fails."""
    rates = fetch_latest_rates(base)
    if rates and target in rates:
        converted = amount * rates[target]
        print(f"Exchange rate {base}->{target}: 1 {base} = {rates[target]:.4f} {target}")
        return converted
    print("Currency not supported or API issue.")
    return None

# Step 3: Bonus visualization (simple trend plot)
def show_trend(base, target):
    """Plots a placeholder trend—upgrade with real history data later."""
    print("Generating trend chart...")
    plt.figure(figsize=(10, 5))
    days = range(1, 8)
    # Fake data for demo; replace with real API calls
    rates = [94.5, 94.7, 94.6, 94.8, 94.9, 94.7, 94.69]  # Recent INR trends
    plt.plot(days, rates, marker='o', linewidth=2, color='green')
    plt.title(f'{base} to {target} Trend (Last 7 Days)')
    plt.xlabel('Days Ago')
    plt.ylabel('Rate')
    plt.grid(True)
    plt.savefig('currency_trend.png', dpi=150, bbox_inches='tight')
    plt.show()
    print("Chart saved as 'currency_trend.png'!")

# Main program: User-friendly loop
if __name__ == "__main__":
    print("🌍 Welcome to Live Currency Converter! (170+ currencies)")
    while True:  # Loop for multiple conversions
        base = input("\nEnter base currency (e.g., USD, EUR, quit to exit): ").upper().strip()
        if base.lower() == 'quit':
            break

        target = input("Enter target currency (e.g., INR): ").upper().strip()
        try:
            amount = float(input("Enter amount: "))
            if amount <= 0:
                print("Please enter a positive amount.")
                continue
        except ValueError:
            print("Invalid number—try again.")
            continue

        result = convert_money(base, target, amount)
        if result:
            print(f"✅ {amount:.2f} {base} = {result:.2f} {target}")
            show_trend(base, target)

    print("Thanks for using the converter! 🚀")